cursor_blink_interval 0
tab_bar_style slant

# Enable window management
enabled_layouts tall,stack,fat,grid,horizontal,vertical,splits

# Navigation shortcuts
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down

# Create splits
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+\ launch --location=vsplit --cwd=current
map ctrl+shift+- launch --location=hsplit --cwd=current

map ctrl+p nth_window -1

map ctrl+shift+p previous_tab

# Close window
map ctrl+shift+w close_window

# Resize windows
map ctrl+shift+r start_resizing_window

# map ctrl+shift+f show_scrollback
map ctrl+shift+f launch --type=overlay --stdin-source=@screen_scrollback nvim

# Highlight active window
active_border_color #4CAF50
inactive_border_color #757575
window_border_width 4px
draw_minimal_borders yes
max_title_length 10

tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{tab.active_oldest_wd}"
